// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChofIoCMsxvjxdISyfGQpBICu1ZFXn6xg',
    appId: '1:95802949748:web:19a1191064b8e359d767a1',
    messagingSenderId: '95802949748',
    projectId: 'tic-tac-toe-a5183',
    authDomain: "tic-tac-toe-a5183.firebaseapp.com",
    databaseURL: 'https://tic-tac-toe-a5183-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-a5183.appspot.com',
    measurementId: 'G-DXBX98VV9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDYdhG1QA2ZCUrZeUSDVmZnCHYEF2_7RKY",
    authDomain: "tic-tac-toe-a5183.firebaseapp.com",
    projectId: "tic-tac-toe-a5183",
    storageBucket: "tic-tac-toe-a5183.appspot.com",
    messagingSenderId: "95802949748",
    appId: "1:95802949748:android:c30640c8942ecd0dbe1121",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAWZEYSsG_7VZOlN7D4yCiST6VvJuSyk',
    appId: '1:95802949748:ios:2d72bb9c45c2e97dd767a1',
    messagingSenderId: '95802949748',
    projectId: 'tic-tac-toe-a5183',
    databaseURL: 'https://tic-tac-toe-a5183-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-a5183.appspot.com',
    androidClientId:
        '95802949748-82ucjkcvdiun5af69tactt38avihkao3.apps.googleusercontent.com',
    iosClientId:
        '95802949748-g1ipd95slna60c6ne9cfq49qugq1ub7d.apps.googleusercontent.com',
    iosBundleId: 'com.sahulat.tictactoe',
  );
}
